"""produktbilder

Revision ID: 00732beba95a
Revises: 5c28949c55c6
Create Date: 2024-10-08 16:34:14.287294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00732beba95a'
down_revision = '5c28949c55c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
