"""Add photo column to Client table

Revision ID: 08b26b2cbea5
Revises: c013eef5db3f
Create Date: 2024-09-20 12:37:59.418017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b26b2cbea5'
down_revision = 'c013eef5db3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
