"""Update client and banner relationship

Revision ID: 4b12793bb45e
Revises: 7b4d75aaea2c
Create Date: 2024-10-07 18:33:38.744621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b12793bb45e'
down_revision = '7b4d75aaea2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galerie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galerie', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
