"""Add Lieferzeiten table

Revision ID: 5c28949c55c6
Revises: eb6e4abfaa8b
Create Date: 2024-10-08 16:16:44.165935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c28949c55c6'
down_revision = 'eb6e4abfaa8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lieferzeiten', schema=None) as batch_op:
        batch_op.alter_column('zeit_von',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('zeit_bis',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lieferzeiten', schema=None) as batch_op:
        batch_op.alter_column('zeit_bis',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('zeit_von',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
