"""Add is_must_popular and is_bestseller to Product model

Revision ID: 76d570ec9376
Revises: 00732beba95a
Create Date: 2024-10-08 16:49:01.703583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d570ec9376'
down_revision = '00732beba95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_must_popular', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_bestseller', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_bestseller')
        batch_op.drop_column('is_must_popular')

    # ### end Alembic commands ###
