"""Added address fields (street, house_number, postal_code, city) to User model

Revision ID: a1b1f64acec9
Revises: 
Create Date: 2024-09-18 14:49:44.462578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b1f64acec9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('house_number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('city')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('house_number')
        batch_op.drop_column('street')

    # ### end Alembic commands ###
