"""Lieferzeiten von Restaurant

Revision ID: baebfdc21548
Revises: 4b12793bb45e
Create Date: 2024-10-08 12:19:52.427448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baebfdc21548'
down_revision = '4b12793bb45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lieferzeiten',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zeit_von', sa.Time(), nullable=False),
    sa.Column('zeit_bis', sa.Time(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lieferzeiten')
    # ### end Alembic commands ###
