"""Made address fields optional

Revision ID: c013eef5db3f
Revises: a1b1f64acec9
Create Date: 2024-09-18 14:55:22.633600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c013eef5db3f'
down_revision = 'a1b1f64acec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('house_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('house_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
