"""Add Lieferzeiten table

Revision ID: eb6e4abfaa8b
Revises: baebfdc21548
Create Date: 2024-10-08 16:07:58.882731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb6e4abfaa8b'
down_revision = 'baebfdc21548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lieferzeiten', schema=None) as batch_op:
        batch_op.alter_column('zeit_von',
               existing_type=mysql.TIME(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('zeit_bis',
               existing_type=mysql.TIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lieferzeiten', schema=None) as batch_op:
        batch_op.alter_column('zeit_bis',
               existing_type=sa.String(length=50),
               type_=mysql.TIME(),
               existing_nullable=False)
        batch_op.alter_column('zeit_von',
               existing_type=sa.String(length=50),
               type_=mysql.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
