"""Create orders and order_items tables

Revision ID: ec951b8eff1b
Revises: 
Create Date: 2024-10-13 22:14:07.501015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec951b8eff1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=8, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=8, scale=2),
               existing_nullable=False)

    op.create_table('order_products',
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_products_ibfk_1'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='order_products_ibfk_2'),
    sa.PrimaryKeyConstraint('order_id', 'product_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
